name: tests
on:
  push:
  workflow_dispatch:

jobs:
  test:
    name: Test Foxtimeout
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '>=1.24' ]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
          cache: false

      - name: Check out code
        uses: actions/checkout@v3

      - name: Run tests
        run: go test -v -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          flags: coverage.txt
  lint:
    name: Lint Foxtimeout
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '>=1.24' ]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
          cache: false

      - name: Check out code
        uses: actions/checkout@v3

      - name: Run linter
        uses: golangci/golangci-lint-action@v3
